# Generated by Django 5.2 on 2025-11-22 03:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peer", "0002_board_moderator_alter_board_creator"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="owner",
        ),
        migrations.AddField(
            model_name="profile",
            name="skills",
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name="profile",
            name="state",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="profile",
            name="town",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="profile",
            name="user",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="zipcode",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="listing",
            name="author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="listings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
