# Generated by Django 5.2.5 on 2025-12-05 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peer', '0003_remove_profile_owner_profile_skills_profile_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
