# Generated by Django 5.2.5 on 2025-12-06 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peer', '0004_alter_customuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='about',
            field=models.TextField(blank=True),
        ),
    ]
