# Generated by Django 5.2.5 on 2025-12-06 10:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peer', '0005_profile_about'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='moderator',
        ),
        migrations.RemoveField(
            model_name='board',
            name='sub_skill',
        ),
        migrations.AddField(
            model_name='board',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='board',
            name='moderators',
            field=models.ManyToManyField(blank=True, related_name='moderators', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='board',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='author',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
