# Generated by Django 5.2.5 on 2025-12-14 23:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peer', '0006_remove_board_moderator_remove_board_sub_skill_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardmessage',
            name='depth',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='boardmessage',
            name='reply_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='peer.boardmessage'),
        ),
    ]
