# Generated by Django 5.2.5 on 2025-12-15 13:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peer', '0008_alter_review_author_alter_review_receiver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardmessage',
            name='poster',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bmessages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='listing',
            name='is_request',
            field=models.BooleanField(default=False, help_text="Check if this is a request for help (otherwise it's an offer)"),
        ),
    ]
